### ISSUE TITLE
Onde é utilizada a rota `/professores/todos`?

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA-FRONT#89]
- Apenas no cadastro?
- Que informações são utilizadas? Apenas o nome?
- Se a resposta for sim para as perguntas acima, por questões de segurança, acredito que essa rota deve retornar apenas uma lista dos nomes. Podemos fazer assim?

**Comment by JameDodgers** [comment]
É usada na tela de perfil do aluno para obter o nome do orientador também. Não seria necessário se o nome do orientador fosse retornado em `alunos/me`. Apenas o nome é utilizado. Quais questões de segurança? Até onde eu sei além do nome só é retornado o e-mail. De qualquer forma, se você retornar um array de objetos como apenas o nome eu não preciso alterar nada no código

**Comment by tauanesales** [comment]
> Não seria necessário se o nome do orientador fosse retornado em alunos/me

Será retornado em `/usuarios/me` na alteração da task https://github.com/tauanesales/Sistema-PGCop-UFBA/issues/79

> Quais questões de segurança?

Vejo como ideal não retornar os IDs internos do banco se eles não forem essenciais para alguma ação (a maioria das coisas devem ocorrer identificando o usuário via token). 

> De qualquer forma, se você retornar um array de objetos como apenas o nome eu não preciso alterar nada no código

Vou criar uma task para isso no backend.


---
Obrigada!

**Comment by JameDodgers** [comment]
Os ids são importantes para as listas, onde são usados como keys, e para serem passados para as rotas que deles dependem. Acho que não há problema algum em eles estarem “expostos” pelas rotas, porque todas elas já são ou deveriam ser consumidas por usuários que já estão autenticados

**Comment by tauanesales** [comment]
Certo! Por ora isso não está previsto para alteração. Ainda preciso ter mais noção da necessidade dos IDs e os impactos que a remoção causaria. Há outras prioridades, então se isso for ser alterado, será lá para o final (e provavelmente não será alterado).
