### ISSUE TITLE
Listar todos os endpoints que não são utilizados pelo front

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA-FRONT#90]

**Comment by JameDodgers** [comment]
@GET professores/me 
@GET professores/{professor_id} (Poderia ser usada para retornar o nome do orientador na tela do perfil do aluno, quando atualmente professores/todos cumpre esse papel)
@DELETE professores/{professor_id} 
@PUT professores/{professor_id} 
@GET professores/email/{professor_id} 
@GET alunos/me 
@GET alunos/{alunoId} 
@DELETE alunos/{alunoId} 
@PUT alunos/{alunoId} (Necessário para tela de atualizar usuário)
@GET alunos/cpf/{aluno_cpf} 
@GET alunos/email/{aluno_cpf} 
@GET tarefas/{tarefaId} 
@DELETE tarefas/{tarefaId} 
@POST tarefas 
@GET tarefas_base/{tarefaId} 
@POST mailer/send (Ainda não foi integrada)
@POST new_password (Ainda não foi integrada)
@POST new_password/auth (Ainda não foi integrada)
@POST new_password/create_token (Ainda não foi integrada)

**Comment by tauanesales** [comment]
Por ora, `professores/me` e `alunos/me` serão removidos na task https://github.com/tauanesales/Sistema-PGCop-UFBA/issues/79.

Para as demais rotas não utilizadas em que não vemos um motivo para existência, consideraremos a remoção quando chegarmos mais perto do produto final.

Obrigada Pablo!
