### ISSUE TITLE
Listar as telas que utilizam cada endpoint

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA-FRONT#91]

**Comment by JameDodgers** [comment]
@POST professores ✅ (Cadastro)
@GET professores/todos ✅ (Cadastro)
@POST alunos ✅ (Cadastro)
@GET alunos/orientador/{orientador_id} ✅ (Perfil do orientador e perfil do coordenador)
@POST token ✅ (Login)
@GET usuarios/me ✅ (Raiz da aplicação)
@GET tarefas/aluno/{alunoId} ✅ (Perfil do Aluno)
@PUT tarefas/{tarefaId} ✅ (Perfil do Aluno)
@GET tarefas_base/courso/{curso} ✅ (Tarefas)
@DELETE tarefas_base/{tarefaId} ✅ (Tarefas)
@POST tarefas_base ✅ (Tarefas)
@PUT tarefas_base{tarefaId} ✅ (Tarefas)
@GET solicitacoes/{status}/{professor_id} ✅ (Perfil do orientador e perfil do coordenador)
@PUT solicitacoes/{solicitacao_id} ✅ (Perfil do orientador e perfil do coordenador)
