### ISSUE TITLE
É necessário um `aluno/me` e `professor/me`?

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA-FRONT#92]
- `usuario/me` poderia ser o único endpoint para todas as telas?

**Comment by JameDodgers** [comment]
Seria o ideal e é inclusive o que eu propus desde o começo, mas o pessoal não quis e ficou desse jeito. Agora, isso está bloqueando alguma coisa? Porque a essa altura eu não vejo muito sentido em refatorar código enquanto houver outras demandas por funcionalidades

**Comment by JameDodgers** [comment]
Não usamos mais `alunos/me` e nem `professor/me` no frontend, ambas foram substituídas por `usuario/me`

**Comment by tauanesales** [comment]
Certo!
