### ISSUE TITLE
Listar necessidades do front-end

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA-FRONT#93]
A maioria das rotas será autenticada agora, pensar nos impactos disso (ver [issues backend](https://github.com/tauanesales/Sistema-PGCop-UFBA/issues))

**Comment by JameDodgers** [comment]
A única rota em que eu achei que a falta de autenticação poderia causar um problema é a de atualizar o aluno que era utilizada pelo professor para remover o aluno como orientador, o que não está funcionando porque a rota não muda o `orientador_id` para `null`, mas como haverá um novo endpoint para fazer isso acredito que não haverá impacto

**Comment by tauanesales** [comment]
Ótimo! Obrigada Pablo!
